
CREATE TABLE IF NOT EXISTS signup (
	id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	email VARCHAR(100) NOT NULL UNIQUE KEY,
	username VARCHAR(30) NOT NULL UNIQUE KEY,
	password VARCHAR(50) NOT NULL,
	active TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
